config/routes.rb
Rails.application.routes.draw do
 
  get '/', to: "welcomes#index"
  get '/jobs', to: "jobs#index"
  get '/welcomes', to: "welcomes#index"
 

end

app/models/city.rb
class City < ActiveRecord::Base
  validates :name, presence: true
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :city
  
  validates :title, :description, :state, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    titles = ["Ruby on Rails Developer", "Junior Developer", "RoR Web Developer", "Senior Rubyisty", "Ruby Programmer", 
              "Ruby on Rails Developer", "Junior Developer", "RoR Web Developer", "Senior Rubyisty", "Ruby Programmer"] 
    pay = %w($100000 $87000 $45000 $67000 $123000 $1000000 $58000 $79000 $97000 $65000)
    remote_chance = %w(yes no yes yes no yes yes yes no no)
    @filler = titles.zip(pay, remote_chance)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
    cities = %w(Denver Chicago Austin Orlando Philadelphia Boston Houston Dallas Oakland Tampa)
    emps = [25, 20, 18, 17, 15, 15, 7, 6, 5, 1]
    salary = %w($125000 $115000 $100000 $97000 $95000 $90000 $87000 $78000 $76000 $65000)
    remotes = %w(Quickleft Thoughtbot Aetna Bonobos IBM Google DISH Tek Cyber Disney)
    @jobs = cities.zip(emps, salary, remotes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/jobs/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="jobs.scss">  
  </head>
  <body>
    <div class="welcome-page-content">
      <%= render 'partials/header' %>
        <div class="city-jobs">
          <table>
            <tr>
              <th>Job Title</th>
              <th>Salary</th>
              <th>Remote Option</th>
            </tr>
              <% @filler.each do |filler| %>
                <tr>
                  <td><%= "#{filler[0]}" %></td>
                  <td><%= "#{filler[1]}" %></td>
                  <td><%= "#{filler[2]}" %></td>
                </tr>
              <% end %>
          </table>
        </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTrail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_header.html.erb
<header>
  <div class="login-button">
    <%= link_to "Login", jobs_path %>
  </div>
  <h1><%= link_to "Rails Trail", welcomes_path %></h1>
  <h3>Tracking Ruby on Rails Jobs Nationwide</h3>
</header>

app/views/welcomes/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="welcomes.scss">  
  </head>
  <body>
    <div class="welcome-page-content">
      <%= render 'partials/header' %>
     <div class="tables">
        <div class="top-ten-table">
          <table>
            <h5>Top 10 Cities</h5>
            <tr>
              <th>Location</th>
              <th>Jobs</th>
            </tr>
            <% @jobs.each do |job| %>
              <tr>
                <td><%= link_to "#{job[0]}", jobs_path  %></td>
                <td><%= "#{job[1]}" %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="top-ten-pay">
          <table>
            <h5>Top Pay Locations</h5>
            <tr>
              <th>Location</th>
              <th>Pay</th>
            </tr>
            <% @jobs.each do |job| %>
              <tr>
                <td><%= link_to "#{job[0]}", jobs_path %></td>
                <td><%= "#{job[2]}" %></td>
              </tr>
            <% end %>
          </table>
        </div>
        <div class="top-ten-remote">
          <table>
            <h5>Remote Jobs</h5>
            <tr>
              <th>Company</th>
            </tr>
            <% @jobs.each do |job| %>
              <tr>
                <td><%= link_to "#{job[3]}", jobs_path %></td>
              </tr>
            <% end %>
          </table>
        </div>

      </div>
    </div>
  </body>
</html>

  
  